---
title: Social Media Planner
timezone: UTC
email: your-email@example.com
description: A curated collection of ideas for your next social media post.
baseurl: '/'
url: 'http://gosocialplanner.com/'
twitter_username: posty_sike
github_username: posty_sike
plugins:
- jekyll-feed
google_analytics: false
